### ISSUE TITLE
louvain not declared as dependency

### ISSUE THREAD

**Issue by pcm32** [SCCAF/sccaf#1]
On a fresh installation, I get the following error

```
>>> from SCCAF import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pmoreno/Development/sccaf.sccaf/SCCAF/__init__.py", line 25, in <module>
    import louvain
ModuleNotFoundError: No module named 'louvain'
```

**Comment by chichaumiau** [comment]
This is a problem with SCANPY, we can add as dependency, but not a problem with SCCAF.

**Comment by pcm32** [comment]
I have added this in #4
