### ISSUE TITLE
problem with SCCAF installation using conda

### ISSUE THREAD

**Issue by mkrzak** [SCCAF/sccaf#41]
Hello,
I have problem when SCCAF is installed using conda. conda install SCCAF seem successful but Im getting error when importing SCCAF in python: 
`>>> import SCCAF
/home/ubuntu/miniconda3/envs/python_env/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/python_env/lib/python3.7/site-packages/SCCAF/__init__.py", line 75, in <module>
    '#000000', ] + default_26
NameError: name 'default_26' is not defined`

Do you have any idea what can cause the issue ? Installed under python version 3.7.7.
Pip installation works fine just problem with conda.

**Comment by cynthier** [comment]
@mkrzak just go into the corresponding file /lib/python3.12/site-packages/SCCAF/__init__, and delete the variable "default_26".
